### PR TITLE
changed deprecated range(at:) to new rangeAt

### PR DESCRIPTION
**Pull request by kobeumut**

### CODE REVIEW

**Comment by 9to6** [comment]
Plz merge this PR.

**Comment by tid-kijyun** [comment]
What are you using the Swift version?
It seems that it has not been changed in the latest version(4.1.2 and 3.3).

**Comment by 9to6** [comment]
@tid-kijyun Sorry, it's my fault. I thought i use swift4 when I compile Kanna. But when I checked it again, It' not.
I used Kanna version 4.0, Kanna was compiled by swift 3.3.
Sorry and thank you for your replying.

**Comment by kobeumut** [comment]
Yeah i see wrong swift version that i used the project. It's version 3.3. So i changed the codes that situation. Please check new codes.

**Comment by tid-kijyun** [comment]
@kobeumut Thank you for your PR. I want to merge this PR into the master branch.
However, there are two problem remaining.

1. **In Swift 3.3 for Linux version, this method has not been changed.** 😞
2. Please use rebase to make one commit.

Would you please consider these and fix it?

I think that it will be like this:

```swift
#if swift(>=4.0) || os(Linux)
let range = result.range(at: at)
#else
let range = result.rangeAt(at)
#endif
```

----

Actually, This problem has been fixed in `feature/v3.0.0` branch (for Swift 3.x).
But, I forgot the task to integrate into the master branch. Thanks to you, I remembered it.

https://github.com/tid-kijyun/Kanna/blob/50b2fa6c8d2341a693b5256624257c58c4502142/Sources/Kanna/CSS.swift#L163-L167

Thanks

**Comment by tid-kijyun** [comment]
Sorry for taking so long. I've just merged this PR.
I simplified the commit and corresponded to the Linux version.

Thanks for your PR.

**Pull request merged**
